language: rust
before_script:
- rustup component add rustfmt-preview
- (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
- (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
- cargo install-update -a
cache:
  - cargo
rust:
- beta
- nightly
matrix:
- fast_finish: true
- allow_failures:
  - nightly
script:
- cargo build
- cargo fmt --all -- --check
- cargo test --all
- mdbook build ./book/

env:
  RUSTINFRA_DEPLOY_DIR: book/book
import:
  - rust-lang/simpleinfra:travis-configs/static-websites.yml
