language: rust
before_script:
- rustup component add rustfmt-preview
- cargo install --vers "^0.4.5" mdbook
cache:
  - cargo
rust:
- beta
- nightly
matrix:
- fast_finish: true
- allow_failures:
  - nightly
script:
- cargo build
- cargo fmt --all -- --check
- cargo test --all
- mdbook build ./book/

env:
  RUSTINFRA_DEPLOY_DIR: book/book
import:
  - rust-lang/simpleinfra:travis-configs/static-websites.yml
