[package]
name = "polonius"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]

[dev-dependencies]
assert_cli = "0.5.4"

[dependencies]
abomonation = "0.5.0"
abomonation_derive = "0.3.0"
differential-dataflow = "0.5.0"
failure = "0.1.1"
timely = "0.5.1"
fxhash = "0.2.1"
structopt = "0.2.8"
clap = "2.31.2"
histo = "0.1.0"
